### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by shakram02** [FlowGrid/flowgrid#3]
Thank you for developing `flowgrid`

Can you please add a License to the repo so other people know how they should be using it if they want to modify/redistribute your code?

MIT License is used by many open source projects as it's the most permissible license.

Thanks,

**Comment by stefanhaustein** [comment]
Added Apache, hope that's sufficiently liberal O:)
Note that the legacy dir already has a GNU license, let me know it that's an issue

**Comment by shakram02** [comment]
thanks :+1:
